kind = "DojoModel"
class_hash = "0x4a6b4db5132c80cbf278d0dcaf1e885cc3fabb547bfdf73c188d61257646098"
original_class_hash = "0x4a6b4db5132c80cbf278d0dcaf1e885cc3fabb547bfdf73c188d61257646098"
abi = "manifests/dev/base/abis/models/dojo_starter-Moves-2a29373f.json"
tag = "dojo_starter-Moves"
manifest_name = "dojo_starter-Moves-2a29373f"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "remaining"
type = "u8"
key = false

[[members]]
name = "last_direction"
type = "Direction"
key = false

[[members]]
name = "can_move"
type = "bool"
key = false
